from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors


def generate_report(data, filename):

    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    heading_style = styles["Heading2"]
    body_style = styles["BodyText"]

    title_style.textColor = colors.HexColor("#2563EB")
    heading_style.textColor = colors.HexColor("#0EA5E9")

    content = []

    # Title
    content.append(
        Paragraph(
            "🚀 IntelliCareer AI Report",
            title_style
        )
    )

    content.append(
        Paragraph(
            "AI-Powered Career Analysis",
            body_style
        )
    )

    content.append(
        Spacer(1, 20)
    )

    # Sections
    for key, value in data.items():

        content.append(
            Paragraph(
                key,
                heading_style
            )
        )

        content.append(
            Spacer(1, 5)
        )

        content.append(
            Paragraph(
                str(value),
                body_style
            )
        )

        content.append(
            Spacer(1, 15)
        )

    # Footer
    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by IntelliCareer AI",
            body_style
        )
    )

    pdf.build(content)